# Решение_оптимизационных задач Scipy

In [1]:
from scipy import optimize

In [17]:
def f(x):
    return(.5*(1 - x[0])**2 + (x[1] - x[0]**2)**2)
print(f([1,1]))

0.0


In [18]:
result = optimize.brute(f,((-5,5),(-5,5))) #перебор
print(result)

[0.99999324 1.00001283]


In [19]:
print(optimize.differential_evolution(f, ((-5,5), (-5,5))))

     fun: 7.395570986446986e-32
 message: 'Optimization terminated successfully.'
    nfev: 3663
     nit: 121
 success: True
       x: array([1., 1.])


In [20]:
import numpy as np

def g(x):
    return(np.array((-2*.5*(1 - x[0]) - 4*x[0]*(x[1] - x[0]**2), 2*(x[1] - x[0]**2))))

In [21]:
print(optimize.check_grad(f,g,[2,2]))

2.384185791015625e-07


In [24]:
print(optimize.fmin_bfgs(f,[2,2], fprime=g))

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 8
         Function evaluations: 9
         Gradient evaluations: 9
[1.00000582 1.00001285]


In [25]:
print(optimize.minimize(f,[2,2]))

      fun: 1.7838045907468558e-11
 hess_inv: array([[0.95489061, 1.90006632],
       [1.90006632, 4.27872378]])
      jac: array([9.88093227e-07, 2.41749084e-06])
  message: 'Optimization terminated successfully.'
     nfev: 36
      nit: 8
     njev: 9
   status: 0
  success: True
        x: array([1.00000573, 1.00001265])


In [26]:
print(optimize.minimize(f,[2,2], method = 'BFGS', jac=g))

      fun: 1.8414093407262628e-11
 hess_inv: array([[0.95489113, 1.90006768],
       [1.90006768, 4.27872719]])
      jac: array([9.88085521e-07, 2.41739812e-06])
  message: 'Optimization terminated successfully.'
     nfev: 9
      nit: 8
     njev: 9
   status: 0
  success: True
        x: array([1.00000582, 1.00001285])


In [27]:
print(optimize.minimize(f,[2,2], method = 'Nelder-Mead'))

 final_simplex: (array([[0.99998568, 0.99996682],
       [1.00002149, 1.00004744],
       [1.0000088 , 1.00003552]]), array([1.23119954e-10, 2.50768082e-10, 3.59639951e-10]))
           fun: 1.2311995365407462e-10
       message: 'Optimization terminated successfully.'
          nfev: 91
           nit: 46
        status: 0
       success: True
             x: array([0.99998568, 0.99996682])


In [38]:
x = np.ndarray(shape=(4,4), dtype=float, order='F')
print(x)

[[3.69748086e-288 2.46442722e-288 2.66965406e-288 3.07845273e-288]
 [2.66962900e-288 4.45470577e-308 2.97747553e-288 1.64352453e-288]
 [7.79230813e-308 2.15657913e-288 3.18106615e-288 2.46441626e-288]
 [2.46441782e-288 3.69745581e-288 3.69418338e-288 2.27481459e-311]]


In [61]:
import pandas as pd
import numpy
df1 = pd.DataFrame([[np.nan, 2, np.nan, 0], [3, 4, np.nan, 1], [np.nan, np.nan, np.nan, 5], [np.nan, 3, np.nan, 4]], columns=list('ABCD'))

In [62]:
print(df1)

     A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  NaN  NaN NaN  5
3  NaN  3.0 NaN  4


In [63]:
df1.fillna('', inplace=True)
print(df1)

   A  B C  D
0     2    0
1  3  4    1
2          5
3     3    4
